server:
  maxThreads: 1024
  applicationConnectors:
  - type: http
    port: 9000
    useServerHeader: true
    useDateHeader: true
    idleTimeout: 30 seconds
    acceptorThreads: 10
    selectorThreads: 20
  adminConnectors:
  - type: http
    port: 9001
    useServerHeader: true
    useDateHeader: true
    idleTimeout: 30 seconds
    acceptorThreads: 1
    selectorThreads: 2

logging:
  level: INFO
  loggers:
    "org.hibernate": ERROR
  appenders:
    - type: console
      logFormat: "%date %highlight(%-5level) [%thread] %cyan(%logger{10}) [%X{id}] %msg%n"
    - type: file
      currentLogFilename: /var/log/elearning/elearning.log
      archive: true
      archivedLogFilenamePattern: /var/log/elearning/elearning-%i.log.gz
      archivedFileCount: 10
      maxFileSize: 100MB
      timeZone: IST
      logFormat: "%date %level [%thread] %logger{10} [%X{id}] %msg%n\n"

elearningMasterDataSource:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost/Elearning?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 100
  properties:
      charSet: UTF-8
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.hbm2ddl.auto: update
      hibernate.generate_statistics: false
  checkConnectionWhileIdle: false
  maxConnectionAge : 10s
  checkConnectionOnBorrow: true
